version: '3.7'

services:
  frontend:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: lukschrodt/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8005:80
  backend:
    mem_limit: 512M
    cpus: 0.2

    restart: unless-stopped
    image: lukschrodt/backend:latest
    container_name: backend
    ports:
      - 8090:8080
    env_file: .env.local
    depends_on:
      - db
  db:
    mem_limit: 128m
    cpus: 0.05

    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
